### ISSUE TITLE
I installed the tutorial on win10 and run the pen_3d demo

### ISSUE THREAD

**Issue by 19920716** [SpectacularAI/sdk-examples#1]
C:/Users/Administrator/Desktop/sdk-examples/python/oak/pen_3d.py:18: DeprecationWarning: setRectifyMirrorFrame() is deprecated.
  vio_pipeline = spectacularAI.depthai.Pipeline(pipeline)[](url)

rgb pictures only rgb, no pen.

**Comment by qwe5788319** [comment]
![1111](https://user-images.githubusercontent.com/19903385/139790820-5c8e509c-6000-44d7-b8d6-7bf38a22e1cd.png)
#

**Comment by qwe5788319** [comment]
![222](https://user-images.githubusercontent.com/19903385/139790915-0c384fde-a510-41f1-91c0-511b98e58987.png)
Is my environment version wrong?

**Comment by oseiskar** [comment]
Hi Andy!

In the pen example, the "ink" activates when you completely cover the RGB camera with your finger (so that the "rgb" image looks completely black or very dark). Did you try that?

To verify that your setup is correct, also try the `vio_visu.py` example. It's otherwise like the pen example but the "ink" is always active and you do not have to cover the color camera.

**Comment by 19920716** [comment]
Hi @oseiskar 
I tried it, there is no drawing function, mixed_reality.py runs normally, but the FPS is a bit low.

**Comment by Bercon** [comment]
Hi @19920716, I tried the example with same dependency versions as you have on Windows 10. The example seems to work fine despite giving the deprecation warning.
* Do you see the orange dot that marks the current position of the pen/device?
* When covering the RGB middle camera, it has to be really well covered, showing an almost completely black image to properly trigger the ink function and leaving a trail
